### DISCUSSION TITLE
Best way to specify multiple `artifactContentType`s?

### DISCUSSION THREAD

**Discussion by MrAlex94** [ncipollo/release-action#133] [Q&A]
What is the best way (if there even is one?) to specify multiple `artifactContentType`s?

For example:

```
artifacts: "Setup.exe,Setup.dmg,setup.tar.bz2"
artifactContentType: "application/vnd.microsoft.portable-executable,application/x-apple-diskimage,application/zip"
```

Doesn't work of course - it sets the `content_type` to `application/vnd.microsoft.portable-executable,application/zip`.

The only way I can think of is to use multiple-steps for each file - but that seems like a less than ideal way.

**Comment by ncipollo** [comment]
There isn't really a way to specify multiple content types. The complexity comes from the fact that `artifacts` can actually be a set of glob paths (ex - `*.exe`) and there wouldn't really be a way you could map those from the action input. I usually just leave this field blank so they all default to `raw`.

**Comment by andrew-pickin-epi** [comment]
Could there not be a enhancement such as
```
artifact_list:
  - content_type: "application/gzip" 
    path: "*.tar.gz"
  - content_type: "text/plain"
    path: "*.txt"
```
