### DISCUSSION TITLE
Required authorization - 404 Error

### DISCUSSION THREAD

**Discussion by fiddlermikey** [ncipollo/release-action#233] [Q&A] [answered]
Is there any troubleshooting I can do to get past this 404 error I am getting? I am trying to use a script in a repo to launch a reusable workflow in another repo which targets a third repo to download, modify, and replace the release zip file. Everything works until I attempt to check in the modified zip file using the release-action workflow. 

I created a PAT for my user that gives full Repo access (private and public). I also created a secret for my Org called CODESIGN_TOKEN, the value was pasted from my PAT key and SSO was enabled.

Calling workflow passes the repo and the file that needs to be modified and the secret.token
```
jobs:
  call-sign-binaries:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: ..../sign-binaries.yml@add-sign-process
    with:
      signFile: IntegrationSandbox.dll
      targetRepo: integration-sandbox
    secrets: 
      token: ${{ secrets.CODESIGN_TOKEN }}
```

The sign-binaries workflow gets called and a series of workflows and run statements continue until I get an error with this part of the workflow. Am I passing something incorrectly? Is my PAT setup incorrectly? Any help would be appreciated.
```
name: Sign Binary File Test
on: 
  workflow_call:
    inputs:
      signFile: 
        description: The file that will be signed. # TODO: Need to make this work for multiple, maybe
        required: true
        type: string
      targetRepo: 
        description: The name of the repository to target with signing
        required: true
        type: string
    secrets:
      token:
        description: 'Secret token from caller workflow to access private packages'
        required: true
.... More stuff to download, extract, modify, and compress the archive.
      - name: find latest tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: keyfactor/${{ inputs.targetRepo }}  
          releases-only: true  
        id: latestReleaseTag  
     - name: Upload Release Asset (x64)
        if: success()
        id: upload-release-asset
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          repo: keyfactor/${{ inputs.targetRepo }} 
          token: ${{ secrets.token }}
          allowUpdates: true
          artifacts: ${{ github.workspace }}\${{ env.releaseArtifactName }}
          name: ${{ env.releaseArtifactName}}
          artifactContentType: application/zip
          replacesArtifacts: true
          tag: ${{ steps.latestReleaseTag.outputs.tag }}
```
