### DISCUSSION TITLE
is it possible to update existing release "commit"?

### DISCUSSION THREAD

**Discussion by ReenigneArcher** [ncipollo/release-action#270] [Q&A] [answered]
As the title states, is it possible to update an existing release commit hash? Additionally, the time it was created?

![image](https://user-images.githubusercontent.com/42013603/198840588-b5449b3b-85ea-4bba-a3ce-621578324092.png)

Time for assets is updated when they are replaced, so that is great!

I am passing the commit manually, which matches the latest commit in the branch.
```yml
      - name: Create/Update GitHub Release
        if: ${{ needs.setup_release.outputs.create_release == 'true' }}
        uses: ncipollo/release-action@v1
        with:
          name: ${{ needs.setup_release.outputs.release_name }}
          tag: ${{ needs.setup_release.outputs.release_tag }}
          commit: ${{ needs.setup_release.outputs.release_commit }}
          artifacts: "*artifacts/*"
          token: ${{ secrets.GH_BOT_TOKEN }}
          allowUpdates: true
          body: ${{ needs.setup_release.outputs.release_body }}
          discussionCategory: announcements
          prerelease: ${{ needs.setup_release.outputs.pre_release }}
```
