### DISCUSSION TITLE
generateReleaseNotes not working for me

### DISCUSSION THREAD

**Discussion by Lindsay-Mathieson** [ncipollo/release-action#309] [Q&A]
As per the title, I'm successfully generating a release on a new tag, but it has no release notes. If I do it manually via github, the release notes are there.
One thing I guess may be affecting it - I'm releasing to a different repository.

```
- name: Upload Release
      if: startsWith(github.ref, 'refs/tags/Release')
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "***,***"
        token: '${{ secrets. RELEASE }}'
        generateReleaseNotes: true
        repo: Release
        name: ${{ env.RELEASENAME }}
        allowUpdates: true

```

## Build output
```
Run ncipollo/release-action@v1.12.0
  with:
    artifacts: ****,****
    token: ***
    generateReleaseNotes: true
    repo: Release
    name: *****
    allowUpdates: true
    makeLatest: legacy
    omitBody: false
    omitBodyDuringUpdate: false
    omitDraftDuringUpdate: false
    omitName: false
    omitNameDuringUpdate: false
    omitPrereleaseDuringUpdate: false
    removeArtifacts: false
    replacesArtifacts: true
    skipIfReleaseExists: false
    updateOnlyUnreleased: false
```
