### DISCUSSION TITLE
Any opportunity to use it without tagging?

### DISCUSSION THREAD

**Discussion by krupitskas** [ncipollo/release-action#35] [Q&A] [answered]
Hey! I want to use this action just for "workflow_dispatch" builds, without creating any tags. But right now I see next:
```
Create Release
Error undefined: No tag found in ref or input!
```
Code:
```
        - uses: ncipollo/release-action@v1
          with:
            name: "Dev Build: ${{ env.GITHUB_HEAD_REF_SLUG }} ${{ env.GITHUB_SHA_SHORT }}"
            artifacts: "linux-deios.zip" # macos-deios.zip, windows-deios.zip,
            token: ${{ secrets.GITHUB_TOKEN }}
            draft: true
            allowUpdates: false
            body: |
              "Notes: ${{ github.event.inputs.notes }}"
              "Branch name: ${{ env.GITHUB_HEAD_REF_SLUG }}"
              "GitHub SHA short: ${{ env.GITHUB_SHA_SHORT }}"
              "GitHub SHA: ${{ env.GITHUB_SHA }}"
```

**Comment by ncipollo** [comment, marked as answer]
Hi!
Yeah, you can just provide the `tag` input argument to it. This can point to an existing tag, or a new one. If it's a new one you can use `commit` to indicate where the tag should be created from. I think the API works if you don't provide this, though I'm not certain which commit it will use (I'm guessing the HEAD of your primary branch).

Ultimately a github release is tightly coupled with a tag, so you will need to provide _some_ tag to it.

**Reply by krupitskas** [reply]
So am I right that such code should work?

```
        - uses: ncipollo/release-action@v1
          with:
            name: "Dev Build: ${{ env.GITHUB_HEAD_REF_SLUG }} ${{ env.GITHUB_SHA_SHORT }}"
            artifacts: "linux-deios.zip" # macos-deios.zip, windows-deios.zip,
            token: ${{ secrets.GITHUB_TOKEN }}
            draft: true
            allowUpdates: true
            replacesArtifacts: true
            tag: dev-release
            body: |
              "Notes: ${{ github.event.inputs.notes }}"
              "Branch name: ${{ env.GITHUB_HEAD_REF_SLUG }}"
              "GitHub SHA short: ${{ env.GITHUB_SHA_SHORT }}"
              "GitHub SHA: ${{ env.GITHUB_SHA }}"
```

Actually pushing it right now to test..

Idea is here to reuse same release for dev builds, create new tag called dev-release and replace everything

**Reply by elect86** [reply]
> I think the API works if you don't provide this, though I'm not certain which commit it will use (I'm guessing the HEAD of your primary branch).

Hey Nick,

I'm trying to release anyway without providing a tag:
```
      - name: 🛎️ Create release
        if: strategy.job-index == 0
        uses: ncipollo/release-action@v1
        with:
          artifacts: ~/jdk-linux-x64${{ matrix.artifact }}/jdk-${{ env.JDK_VERSION }}-internal+0_linux-x64_bin${{ matrix.artifact }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.gitDescribe }}
          body: ${{ github.actor }}-${{ env.GITHUB_SHA_SHORT }}
```

But I still get:

> Error: Error undefined: No tag found in ref or input!
