### DISCUSSION TITLE
Is it possible to update existing release?

### DISCUSSION THREAD

**Discussion by ravgeetdhillon** [ncipollo/release-action#38] [Q&A] [answered]
I have created a release using

```yml
- name: Create Release
  uses: ncipollo/release-action@v1
  with:
    name: ${{ env.next_version }}
    tag: ${{ env.next_version }}
    commit: master
    allowUpdates: true
    prerelease: false
    draft: false
    token: ${{ secrets.GITHUB_TOKEN }}
```

Let us suppose that it created a tag and release for `2.0.0`.

Now next time when I run my workflow I want to update this `2.0.0` release and create a new one as well e.g. `2.0.1`. How do I perform this step? I have performed the following operation but it gave me:

```
Error 422: Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"} Errors: - Release already exists.
```

This is the workflow which I am trying to run.

```
# create a new release
- name: Create Release
  uses: ncipollo/release-action@v1
  with:
    name: ${{ env.next_version }}
    tag: ${{ env.next_version }}
    commit: master
    allowUpdates: true
    prerelease: false
    draft: false
    token: ${{ secrets.GITHUB_TOKEN }}

# update the existing one
- name: Create Release
  uses: ncipollo/release-action@v1
  with:
    tag: ${{ env.major_version }}
    commit: master
    token: ${{ secrets.GITHUB_TOKEN }}
```
