### DISCUSSION TITLE
Show example to release to another repo

### DISCUSSION THREAD

**Discussion by manongjohn** [ncipollo/release-action#41] [Q&A]
I have an organization account with multiple repositories.  The main repository builds artifacts and I'd like to take the artifact from the main builds and create a prerelease in another repo within the same organization account.

I was wondering if you could provide an example of how to set that up?  I'm not exactly sure what I should be putting for `repo` and do I still need to create a personal access token or will the GITHUB_TOKEN still work since it's under the same organization?

Thanks

**Comment by manongjohn** [comment]
Nevermind. I did get it to work.  Would be nice in your README to have an example showing all options.

At any rate, thank you for creating this action.

**Reply by nerdCopter** [reply]
@manongjohn , might you share how you succeeded?  even after some hints, i'm failing:
```
Error: Error 422: Validation Failed: {"resource":"Release","code":"invalid","field":"target_commitish"}
Errors:
- The target_commitish field on Release is an invalid format.
```

**Reply by manongjohn** [reply]
Sure. Below is the step from my Linux workflow. The macOS & Windows are pretty much the same except the artifact.

My application is built in repo `tahoma2d/tahoma2d` when PRs are merged to my master.  I have 3 workflows, 1 for each environment which creates a "nightly" version in `tahoma2d/tahoma2d_nightlies`. Whomever finishes first will create the release. The others will just update the release by adding the artifact, leaving name and body alone.

```
      - name: Create Nightlies Release
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: false
          artifacts: toonz/build/Tahoma2D-linux-${{ matrix.compiler }}.tar.gz
          artifactContentType: "raw"
          body: ${{ github.event.head_commit.message }}
          name: ${{ env.NIGHTLYDATETIME }}
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          owner: tahoma2d	  
          prerelease: true
          replacesArtifacts: true
          repo: tahoma2d_nightlies
          tag: nightly-${{ github.sha }}
          token: ${{ secrets.TAHOMA2D_TOKEN }}
```

Hope that helps
