### DISCUSSION TITLE
Need recipe for `nightly` build with updated date in GitHub

### DISCUSSION THREAD

**Discussion by jibbers42** [ncipollo/release-action#419] [Q&A]
I see several questions around this topic and maybe I've missed the answer, but I'm looking for how to replace a release with an updated one, including the date in GitHub (see screenshot):
![image](https://github.com/ncipollo/release-action/assets/797824/fc221fa9-91cf-4128-8fd5-826e4b66a7aa)

I've managed to get artifacts replaced with newer ones, include the source I believe, by updating the `nightly` tag.

The relevant sections of my workflow are:
```yaml
name: Nightly Build

on:
  schedule:  # schedule runs against last commit on default branch (master)
    - cron: '0 9 30 * *'  # Daily at 9:30 UTC

... other job ...

  update_nightly_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Update Nightly Tag
        uses: richardsimko/update-tag@v1.0.11
        with:
          tag_name: nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_and_release:
    runs-on: ubuntu-latest
    steps:

... test and build steps ...

      - name: Create Nightly Release (pre-release)
        uses: ncipollo/release-action@v1.14.0
        with:
          name: Nightly Development Build
          tag: nightly
          commit: 'refs/heads/master'
          prerelease: true
          makeLatest: false
          generateReleaseNotes: true
          artifactErrorsFailBuild: true
          removeArtifacts: true
          allowUpdates: true
          artifacts: build/app/outputs/my-release/*
```

Do I need to delete the existing `nightly` build in some way is there a way to replace it so I get only new artifacts, new source, and an updated display date? What's the recipe?

**Comment by ncipollo** [comment]
I don't know of a way to change that date via the GitHub API. I'm not sure exactly sure what their internal logic for it is (might just be when release was first created).

**Reply by jibbers42** [reply]
Oh I see - I thought for sure I was just doing it wrong. Well, in that case I think for now I'll just add the date to the label. Thanks for taking the time to let me know!

something like (untested):
```yaml
...

      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

...

      - name: Create Nightly Release (pre-release)
        uses: ncipollo/release-action@v1
        with:
          name: Nightly Development Build (${{ env.CURRENT_DATE }})
          tag: nightly

...
```
