### DISCUSSION TITLE
Release notes generation always lists all changes

### DISCUSSION THREAD

**Discussion by stefanschulte** [ncipollo/release-action#428] [Q&A]
Hi there,
is it possible to limit the release notes created to only list the differences/additions compared to the last release prior to the new release?
With my default configuration, it always lists the entire changelog from beginning of time for the repo. I'm using the github release notes release.yml, but I doubt that has any influence?

My config:
```yaml
- name: Create release
      uses: ncipollo/release-action@1e3e9c6637e5566e185b7ab66f187539c5a76da7 # v1.13.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: "v${{ env.version }}"
        generateReleaseNotes: true
 ```
