### DISCUSSION TITLE
How can I parse environment variable in my `body`?

### DISCUSSION THREAD

**Discussion by elect86** [ncipollo/release-action#62] [Q&A] [answered]
As titled, I'd like to know how I can parse github envs in `body`, that is
```
      - name: 🛎️ Create release
        if: strategy.job-index == 0
        uses: ncipollo/release-action@v1
        with:
          artifacts: ~/jdk-linux-x64${{ matrix.artifact }}/jdk-${{ env.JDK_VERSION }}-internal+0_linux-x64_bin${{ matrix.artifact }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: $GITHUB_ACTOR-$GITHUB_SHA
          body: ${$GITHUB_ACTOR-$GITHUB_SHA}
          draft: true
```
