### ISSUE TITLE
Multiple artifact (wildcard) support

### ISSUE THREAD

**Issue by tsl0922** [ncipollo/release-action#1]
This would not work.

```
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: ncipollo/release-action@v1
        with:
          artifact: "bin/*"
          token: ${{ secrets.GITHUB_TOKEN }}
```
