### ISSUE TITLE
Error 401: Bad credentials

### ISSUE THREAD

**Issue by ThatWeirdAndrew** [ncipollo/release-action#10]
I'm trying to use release-action to publish my release to github. When I run the action, it fails with the error: `##[error]Error 401: Bad credentials`. Here is part of the config yml:
```
    - name: Publish release
      env: 
        RELEASENAME: $(date +%y%m%d)
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifact: rootfs/targz/install.tar.gz
        tag: ${RELEASENAME}

```
What did I do wrong?
