### ISSUE TITLE
A basic implementation throws an error with code MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by jeffreylanters** [ncipollo/release-action#101]
**Describe the bug**
A basic implementation thrown an error with code MODULE_NOT_FOUND

```
Run ncipollo/release-action@7461bfe83946fc198f507edec4c13f2cda9102dd
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@actions/github'
Require stack:
- /home/runner/work/_actions/ncipollo/release-action/7461bfe83946fc198f507edec4c13f2cda9102dd/lib/Main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/ncipollo/release-action/7461bfe83946fc198f507edec4c13f2cda9102dd/lib/Main.js:31:29)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/ncipollo/release-action/7461bfe83946fc198f507edec4c13f2cda9102dd/lib/Main.js'
  ]
}
```

**To Reproduce**
- Create a repository
- Added the following step to a new workflow

```
- name: Create Release
  uses: ncipollo/release-action@7461bfe83946fc198f507edec4c13f2cda9102dd
  with:
    name: Release ${{ github.ref }}
    artifacts: module.tgz
    artifactContentType: application/tar
    discussionCategory: Releases
    token: ${{ secrets.GITHUB_TOKEN }}
```

- Run the workflow

**Expected behavior**
For the version to be released.

**Screenshots**
N/A

**System:**
 - OS: GitHub Actions Ubuntu
 - Version: "ubuntu-latest"

**Additional context**
N/A
