### ISSUE TITLE
removeArtifacts doesn't remove artifacts

### ISSUE THREAD

**Issue by Bilge** [ncipollo/release-action#120]
**Describe the bug**
`removeArtifacts` does not remove any files attached to the release. Probably it only works if artifacts are listed explicitly, however I do not list artifacts in this action because I use another action to upload them (that supports renaming on upload).

**To Reproduce**
```yaml
      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          removeArtifacts: true

      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: my.tar.xz
          asset_name: My Product v${{ env.tag }}.tar.xz # This renames the uploaded file.
          asset_content_type: application/x-xz
```

**Expected behavior**
Uploading the same tag/release is idempotent.

**Actual behavior**
>Run actions/upload-release-asset@v1
  Error: Validation Failed

The error message from the upload action is not very clear, but it fails because the artifact already exists, because `ncipollo/release-action` did not remove them, despite being configured to.
