### ISSUE TITLE
after update release, commit id and release time not change

### ISSUE THREAD

**Issue by fcying** [ncipollo/release-action#128]
**Describe the bug**
after update release, `artifacts`, `body` can be changed, but `commit id` and `github-actions released time` not change.

**To Reproduce**
```
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "test"
          commit: master
          allowUpdates: true
          replacesArtifacts: true
          removeArtifacts: true
          artifacts: "test.zip"
	  body: |
            test
```

**Expected behavior**
update commit id and release time
