### ISSUE TITLE
After update, Error 403: Resource not accessible by integration

### ISSUE THREAD

**Issue by Gwindalmir** [ncipollo/release-action#129]
After the most recent update, I get an error when running the action:
Error 403: Resource not accessible by integration

Here's the action:
```
    - uses: ncipollo/release-action@v1
      name: Publish Release
      id: publish-release
      with:
        artifacts: "**/*WorkshopTool*.zip"
        token: ${{secrets.GITHUB_TOKEN}}
        name: Workshop Tool v${{steps.changelog.outputs.version-prefix}}
        tag: v${{steps.changelog.outputs.version}}
        commit: master
        draft: ${{github.event.inputs.draft}}
        prerelease: ${{github.event.inputs.prerelease}}
        allowUpdates: true
        body: |
          Changelog:
          ${{env.CHANGELOG}}
          
```

https://github.com/Gwindalmir/SEWorkshopTool/runs/3874862024?check_suite_focus=true

Output snippet:
```
  with:
    artifacts: **/*WorkshopTool*.zip
    token: ***
    name: Workshop Tool v0.7.14
    tag: v0.7.14-alpha
    commit: master
    draft: true
    prerelease: true
    allowUpdates: true
    body: Changelog:
  - fa365ce Include git hash in logged version output.

[... trimmed ...]  
    omitBody: false
    omitBodyDuringUpdate: false
    omitName: false
    omitNameDuringUpdate: false
    omitPrereleaseDuringUpdate: false
    removeArtifacts: false
  env:
    SOLUTION_FILE_PATH: WorkshopTool.sln
    BUILD_CONFIGURATION: Release
    BUILD_FRAMEWORK: net461
    CHANGELOG: - fa365ce Include git hash in logged version output.
[... more snipped ...]
  - d0fb454 Implement powershell pre-build script to automatically create a link to the SE and ME game binaries. This is an alternative implementation for PR #34. If the game is installed, it will be automatically detected.
Error: Error 403: Resource not accessible by integration
```

**Comment by Gwindalmir** [comment]
Nevermind, apparently I couldn't use GITHUB_TOKEN anymore and had to add a personal access token to my repo.
I did that and the issue has been resolved.

**Comment by florian30491** [comment]
> Nevermind, apparently I couldn't use GITHUB_TOKEN anymore and had to add a personal access token to my repo. I did that and the issue has been resolved. Except now the release is listed as done by me, instead of the action bot.

Hi @Gwindalmir 

do you have an idea, why this was not possible to use anymore ? I am currently facing an similar problem on a GitHub Enterprise server. Did you have this issue on github.com ? 

BR,
Florian

**Comment by Gwindalmir** [comment]
> > Nevermind, apparently I couldn't use GITHUB_TOKEN anymore and had to add a personal access token to my repo. I did that and the issue has been resolved. Except now the release is listed as done by me, instead of the action bot.
> 
> Hi @Gwindalmir
> 
> do you have an idea, why this was not possible to use anymore ? I am currently facing an similar problem on a GitHub Enterprise server. Did you have this issue on github.com ?
> 
> BR, Florian

Unfortunately, no.
I don't understand how they work, and I still get emails from github saying I'm using the wrong type of token in other applications.
I just don't understand what I'm supposed to do.

**Comment by vzhd1701** [comment]
Had the same issue recently. Fixed it by going to project's settings -> actions -> general and setting `Workflow permissions` to `Read and write permissions`.

**Comment by florian30491** [comment]
@MarkEnverus 

> I'm facing the same issue w/ Github.com - i can't even use a personal token - if i do that I get the error "Error: Error undefined: Parameter token or opts.auth is required"

With the newest Version of GitHub Enterprise Server the action is working as expected.

**Comment by pkania-as** [comment]
I'm facing the same problem. The project settings are correct (i.e. `Workflow permissions` to `Read and write permissions`. I also tried using a personal token. Nothing helps.

Here's the action:

```
name: Release

on:
  workflow_dispatch:

jobs:
  build-release:
    name: Release
    runs-on: macos-13
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Publish
        uses: ncipollo/release-action@v1
        with:
          tag: 1.0.1
          commit: 1q2w3e4
```
