### ISSUE TITLE
Support new line separated artifacts syntax

### ISSUE THREAD

**Issue by rgl** [ncipollo/release-action#136]
**Is your feature request related to a problem? Please describe.**

It would pretty interesting to support the same artifact splitting glob syntax as https://github.com/actions/upload-artifact#upload-using-multiple-paths-and-exclusions.

For example, when using upload-artifact/download-artifact/release-action, using new lines to split the globs, we could use the same syntax among those three actions:

```yml
jobs:
  amd64:
    steps:
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: amd64
          path: |
            *.iso
            *.img
  release:
    needs:
      - amd64
      - arm64
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: .
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            *.iso
            *.img
          token: ${{ secrets.GITHUB_TOKEN }}
```

**Describe the solution you'd like**

Add support for splitting the artifacts by new lines:

```yml
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            *.iso
            *.img
```
