### ISSUE TITLE
No tag found in ref or input!

### ISSUE THREAD

**Issue by saurabh47** [ncipollo/release-action#14]
**Error->**
Error undefined: No tag found in ref or input!
![Screenshot 2020-04-21 at 3 06 09 AM](https://user-images.githubusercontent.com/15173289/79803278-4cc0a400-837f-11ea-88ac-800038e9801f.png)

I'm using the source tree for tagging the commits & also tried this command ->
```
git tag v1.0.5
git push origin v1.0.5
git push -u origin master
```
maybe I'm doing something wrong.I'm new to GitHub actions.

workflow file:-
```
name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2.1.0

      - name: Cache node modules
        uses: actions/cache@v1.1.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and npm run build
        run: |
          npm i
          npm run build
      - name: Push Build to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/paper-dj-ui/*"
          token: ${{ secrets.TOKEN }}
```
Thanks & regards,
saurabh

**Comment by ncipollo** [comment]
Hi @saurabh47,

That error is indicating that the action doesn't know which tag to use to create the release. There are a couple of ways to specify the tag: 

# Run your job on tag push
If you check out the example in the readme, you can see how to set this up: https://github.com/ncipollo/release-action#example . 

The important bit is:
```yml
on: 
  push:
    tags:
    - '*'
```

# Explicitly specify the tag as an input argument
You can manually pass in the tag via an input action - see https://github.com/ncipollo/release-action#action-inputs

In your example you would update your workflow to something like this:
```
- name: Push Build to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/paper-dj-ui/*"
          tag: v1.0.5
          token: ${{ secrets.TOKEN }}
```

Given your example above I think you would probably want to go with the first option, since this will automatically work with what seems to be your use case.

**Comment by saurabh47** [comment]
Thank you so much.it is working after specifying
```
on: 
  push:
    tags:
    - '*'
```

**Comment by saurabh47** [comment]
Now I'm getting this error 
**##[warning]Failed to upload artifact dist. EISDIR: illegal operation on a directory, read.**
![Screenshot 2020-04-21 at 11 09 39 PM](https://user-images.githubusercontent.com/15173289/79896240-beebc400-8425-11ea-9e14-a28fb764d08e.png)

```
- name: Push Build to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/paper-dj-ui/*"
```
as you see I have specified artificat directory (dist/paper-dj-ui/*) which contains js files and assets folder.I want to upload this directory as zip file.
**Do I have to zip the build using Linux commands before uploading ?**

**Comment by ncipollo** [comment]
Yeah, you would want to tar up that directory before running the action. 

You might want to include a script within your package.json which generates the tarball (zip). The benefit of having that within your package.json is that then you can reproduce the generated tarball locally for testing.

Here's an example of a repo where I do something similar: https://github.com/ncipollo/tix/blob/master/Makefile#L24

(this is a go repo, but a similar approach would work for a node repo).

**Comment by saurabh47** [comment]
@ncipollo Thank you 😊

**Comment by heypran** [comment]
> Hi @saurabh47,
> 
> That error is indicating that the action doesn't know which tag to use to create the release. There are a couple of ways to specify the tag:
> 
> # Run your job on tag push
> If you check out the example in the readme, you can see how to set this up: https://github.com/ncipollo/release-action#example .
> 
> The important bit is:
> 
> ```yaml
> on: 
>   push:
>     tags:
>     - '*'
> ```
> 
> # Explicitly specify the tag as an input argument
> You can manually pass in the tag via an input action - see https://github.com/ncipollo/release-action#action-inputs
> 
> In your example you would update your workflow to something like this:
> 
> ```
> - name: Push Build to Releases
>         uses: ncipollo/release-action@v1
>         with:
>           artifacts: "dist/paper-dj-ui/*"
>           tag: v1.0.5
>           token: ${{ secrets.TOKEN }}
> ```
> 
> Given your example above I think you would probably want to go with the first option, since this will automatically work with what seems to be your use case.

Hi, I am facing the same error but I am explicitly providing the tag name. I cannot use the auto-trigger as I am generating the tag via another action and that is rerunning the workflow. 
here is my action input--
```
      - name: Create a Release 
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ steps.release_tag.outputs.new_tag }}"
          commit: $GITHUB_SHA
          artifacts: "/*.txt"
          token: ${{ secrets.GIT_TOKEN }}
```

I have been trying to solve this since a long time. What am I doing wrong here?

**Comment by heypran** [comment]
> > Hi @saurabh47,
> > That error is indicating that the action doesn't know which tag to use to create the release. There are a couple of ways to specify the tag:
> > # Run your job on tag push
> > If you check out the example in the readme, you can see how to set this up: https://github.com/ncipollo/release-action#example .
> > The important bit is:
> > ```yaml
> > on: 
> >   push:
> >     tags:
> >     - '*'
> > ```
> > 
> > 
> > # Explicitly specify the tag as an input argument
> > You can manually pass in the tag via an input action - see https://github.com/ncipollo/release-action#action-inputs
> > In your example you would update your workflow to something like this:
> > ```
> > - name: Push Build to Releases
> >         uses: ncipollo/release-action@v1
> >         with:
> >           artifacts: "dist/paper-dj-ui/*"
> >           tag: v1.0.5
> >           token: ${{ secrets.TOKEN }}
> > ```
> > 
> > 
> > Given your example above I think you would probably want to go with the first option, since this will automatically work with what seems to be your use case.
> 
> Hi, I am facing the same error but I am explicitly providing the tag name. I cannot use the auto-trigger as I am generating the tag via another action and that is rerunning the workflow.
> here is my action input--
> 
> ```
>       - name: Create a Release 
>         uses: ncipollo/release-action@v1
>         with:
>           tag: "${{ steps.release_tag.outputs.new_tag }}"
>           commit: $GITHUB_SHA
>           artifacts: "/*.txt"
>           token: ${{ secrets.GIT_TOKEN }}
> ```
> 
> I have been trying to solve this since a long time. What am I doing wrong here?

Okay I got it! This is why it was not working - 
https://github.community/t5/GitHub-Actions/Output-from-one-step-with-ID-to-another-is-empty/td-p/44432
I found a work around. Thank you anyways.

**Comment by UVLabs** [comment]
> Hi @saurabh47,
> 
> That error is indicating that the action doesn't know which tag to use to create the release. There are a couple of ways to specify the tag:
> 
> # Run your job on tag push
> If you check out the example in the readme, you can see how to set this up: https://github.com/ncipollo/release-action#example .
> 
> The important bit is:
> 
> ```yaml
> on: 
>   push:
>     tags:
>     - '*'
> ```
> 
> # Explicitly specify the tag as an input argument
> You can manually pass in the tag via an input action - see https://github.com/ncipollo/release-action#action-inputs
> 
> In your example you would update your workflow to something like this:
> 
> ```
> - name: Push Build to Releases
>         uses: ncipollo/release-action@v1
>         with:
>           artifacts: "dist/paper-dj-ui/*"
>           tag: v1.0.5
>           token: ${{ secrets.TOKEN }}
> ```
> 
> Given your example above I think you would probably want to go with the first option, since this will automatically work with what seems to be your use case.

This should be in the docs

**Comment by andreyluiz** [comment]
Just giving my 5 cents:

I was having this issue when using this action on a reusable workflow. To fix the issue I passed the tag as a parameter to the reusable flow.

```yml
# reusable.yml
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build:
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.tag }}
      # Build application
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.tag }}
```

And then on the caller, passing the tag as parameter:

```yml
# caller.yml
jobs:
  tag:
    # ...
  build:
    needs: tag
    uses: user/repo/.github/workflows/reusable.yml@develop
    if: needs.tag.outputs.app-version != ''
    with:
      tag: ${{ needs.tag.outputs.app-version }}
```

Hope it helps. :)
