### ISSUE TITLE
Feature Request: ability to specify different content types for each artifact

### ISSUE THREAD

**Issue by mscdex** [ncipollo/release-action#148]
Currently it seems we can only specify one content type for all of the given artifacts. It would be nice if we could at least have `artifactContentType` be an array/list where the artifacts with corresponding matching indexes have their content type set appropriately to that particular content type. That way we could do something like this:

```yaml
    - name: 'Upload files to release'
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.ver_tag }}
        artifacts: [path/to/file1.bin.gz, path/to/file2.tar, files.txt]
        artifactContentType: [application/gzip, application/tar, text/plain]
```
