### ISSUE TITLE
separate workflow using on release trigger not firing

### ISSUE THREAD

**Issue by ReenigneArcher** [ncipollo/release-action#166]
**Describe the bug**
When using this action to create a release, separate workflows with the on release trigger are not firing.

**To Reproduce**
1. Use this action to create a new release
2. Have a separate workflow using:
```yaml
name: Release Notifications
on:
  release:
    types: [published]  # also tried `released` and `created`
```
3. On release workflow never fires.

**Expected behavior**
Expect on release trigger to fire.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
