### ISSUE TITLE
Publish release after files are uploaded

### ISSUE THREAD

**Issue by maraf** [ncipollo/release-action#17]
I'm using your great action in combination with a webhook. For this scenario it is quite unfortunate that the release is first published and after that artifacts are uploaded. 

I would like to propose a configuration switch that would, if enabled, create a release as a draft and after artifacts are uploaded, it would publish the release.

If it sounds good to you, I would be interested in delivering a PR.

**Comment by ncipollo** [comment]
Hi @maraf! 

I just want to make sure I understand your use case correctly - do you have a webhook set up to watch for the release being created? If so, I can see how this would be a problem since the hook would trigger before the artifacts were uploaded 🙃 


I'm definitely not opposed to coming up with a solution to support this use case, but I'm wondering if we could solve this in the workflow rather than introducing a new configuration option. In theory we could chain two release actions together. The first would create the release as a draft and upload artifacts, then the second action would update it to be a non-draft release. For example:
```yml
- name: Create Draft release
  uses: ncipollo/release-action@v1
  with:
    allowUpdates: true
    artifacts: "images/*.png,text/*.txt"
    artifactContentType: "raw"
    bodyFile: "body.md"
    draft: true
    replacesArtifacts: true
    token: ${{ secrets.GITHUB_TOKEN }}
- name: Publish release
  uses: ncipollo/release-action@v1
  with:
    allowUpdates: true
    omitBodyDuringUpdate: true
    replacesArtifacts: false
    token: ${{ secrets.GITHUB_TOKEN }}
```
Full example here: https://github.com/ncipollo/actions-playground/blob/master/.github/workflows/tag.yml

The benefit of this approach is that you have more flexibility in how your configure the two actions (and you could actually perform other steps in between the two if needed).
