### ISSUE TITLE
Do not remove release description when updating an existing release

### ISSUE THREAD

**Issue by Koushikphy** [ncipollo/release-action#174]
This action can update an existing release when the tag is same. But during the update it removes any description from the existing tag. 
My action looks like this
```yaml

      - name: Release builds to Github
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts/*/*"
          allowUpdates: true
          tag: v${{ steps.app_version.outputs.current-version}}
          token: ${{ secrets.GITHUB_TOKEN }}
          replacesArtifacts: true
          artifactErrorsFailBuild: true
```
If say I have and release with `v1.11.1` and I have some description with the release. If I use this action with the same tag it updates the file but removes the description. Is it possible to update the release and also keep the existing description?
