### ISSUE TITLE
A new duplicate release is created even when `allowUpdates: true`

### ISSUE THREAD

**Issue by shreyanshp** [ncipollo/release-action#175]
**Describe the bug**
This used to work well, till January end - Feb Start, I believe, however in our workflow I can see that whenever the workflow runs, it creates a new release instead of updating the existing one as it used to

**To Reproduce**

https://github.com/shreyanshp/gitops/blob/trunk/.github/workflows/normal_release_flow.yml
```
- uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        draft: true
        name: "${{ steps.bump-semver.outputs.new_version }}-rc.1 🌈"
        tag: "${{ steps.bump-semver.outputs.new_version }}-rc.1"
        commit: "${{ env.DEFAULT_BRANCH }}"
        body: ${{ steps.changelog.outputs.changelog }} <br /> Services Impacted are <br /> ${{ env.SERVICES_IMPACTED }}
        token: ${{ secrets.Token}}  
        
```

**Expected behavior**

**Screenshots**
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/21307950/155655195-ff82adfc-9272-4e32-8e2a-6161f2b8456f.png">

**Additional context**

https://github.com/shreyanshp/gitops/releases
