### ISSUE TITLE
Error 404 On External Repo

### ISSUE THREAD

**Issue by ThePieMonster** [ncipollo/release-action#182]
**Describe the bug**
When trying to create a release for another repo, a 404 error is generated. The error handling could be more detailed as well.

**To Reproduce**
1. Create a personal access token with the "repo" permission. 
2. Include that token as a secret in the repo.
3. Create a GitHub Action as shown below:

```
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.VERSIONNAME }}
        tag: ${{ env.VERSIONNAME }}
        body: ${{ steps.Changelog.outputs.changelog }}
        token: ${{ secrets.REPO_TOKEN }}
        repo: OtherGitHubAccount/repo.name
```

The output is: `Error: Error 404: Not Found`

**Expected behavior**
The release is created in the specified repo.
