### ISSUE TITLE
Detecting File A Directory

### ISSUE THREAD

**Issue by DEVLOPRR** [ncipollo/release-action#184]
**File is Detected As A Directory**
In this [GitHub Action](https://github.com/DEVLOPRR/imageHub/actions/runs/1964384062) my artifact file is detected as a directory instead of a file.

**To Reproduce**
1. Go to https://github.com/DEVLOPRR/imageHub
2. Fork/Clone It into your GitHub Account
4. Enable Workflow in your Repository
5. Run The 'Create Release' Workflow and Type It any Version
6. See error

**Expected behavior**
Expected Behavior was the file should've been uploaded to github release

**Screenshots**
![image](https://user-images.githubusercontent.com/75035219/157715753-146595c0-3a48-4b49-af35-034be2d7da76.png)

**Desktop (please complete the following information):**
 - OS: XUbuntu
 - Browser: Mozilla Firefox
 - Version: 97.0.2

**Comment by ncipollo** [comment]
The path glob you are using is picking up the `AppImage` directory, you should update it to point to the actual artifacts you want to upload (or tar up AppImage).

**Comment by DEVLOPRR** [comment]
I tried providing the the exact file name too:

```yaml
artifacts: './imageHub-${{github.event.inputs.version}}-x86_64.AppImage'
```

It still doesn't work.

![image](https://user-images.githubusercontent.com/75035219/157913591-2fbf1f3c-ccaf-4a15-b510-ec82f422d7ca.png)

**Comment by vsontsa** [comment]
Hello!

I have the same issue

```
      - name: Release2
        uses: ncipollo/release-action@v1.13.0
        with:
          name: Release ${{ env.VERSION_NUMBER }} (build ${{ env.BUILD_NUMBER }})
          artifactContentType: "raw"
          artifactErrorsFailBuild: false
          artifacts: |
            ${{ github.workspace }}/*.tar.gz
          bodyFile: "CHANGELOG.txt"
          tag: v${{ env.VERSION_NUMBER }}-${{ env.BUILD_NUMBER }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          draft: true
          commit: ${{ github.sha }}
```         

![image](https://github.com/ncipollo/release-action/assets/83598995/7d6462be-3a0a-453d-9fcc-e3723ffbf1f7)
