### ISSUE TITLE
Published release became draft after update

### ISSUE THREAD

**Issue by mahnunchik** [ncipollo/release-action#185]
**Describe the bug**

Published release became draft after update.

**To Reproduce**
1. Create draft release with [release-action](https://github.com/ncipollo/release-action)
2. Publish it manually
3. Update release with option `allowUpdates: true`
4. Published release became draft

**Expected behavior**

It would be great to have option such `changeDraftDuringUpdate` to be able to keep release published during update.

```yml
- uses: ncipollo/release-action@v1
  with:
    tag: v${{ env.VERSION }}
    name: v${{ env.VERSION }}
    draft: true
    changeDraftDuringUpdate: false
    allowUpdates: true
    omitBodyDuringUpdate: true
    omitNameDuringUpdate: true
```
