### ISSUE TITLE
On a new repo a new preview release does not contain release notes

### ISSUE THREAD

**Issue by marcofranssen** [ncipollo/release-action#197]
**Describe the bug**

Release notes are not in the release. Only the tag annotation is in the first release. In the second release the tag annotation is not there.

**To Reproduce**

Following workflow on a new repo does result in a release without release notes.

```yaml
name: Release
on:
  push:
    tags:
      - v*

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: [self-hosted, linux, X64, research]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
        with:
          # if we release often, there will be no more than this amount of commits in a release
          fetch-depth: 50

      - name: Update module docs
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "false"

      - name: Check documentation updated
        run: git diff --quiet >/dev/null 2>&1

      - name: Setup Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16'

      - uses: ncipollo/release-action@v1.10.0
        id: release
        with:
          draft: ${{ contains(github.ref, '-draft') }}
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-alpha') || contains(github.ref, '-beta') }}
          generateReleaseNotes: true
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Workflow notices
        run: echo "::notice title=Release::${{ steps.release.outputs.html_url }}"
```

The workflow is triggered by an annotated tag.

```bash
git tag -sam "Initial release candidate" v0.1.0-rc
git push origin v0.1.0-rc
git commit -m "Some new feature"
git tag -sam "Initial release candidate" v0.1.0-rc2
git push origin v0.1.0-rc2
```

**Expected behavior**

The release also contains release notes based on the commit history. Both releases also contain the annotation.

**Screenshots**

<img width="445" alt="image" src="https://user-images.githubusercontent.com/694733/162695975-42628538-3d9d-45b2-b2fd-87116ca2fbb7.png">

<img width="341" alt="image" src="https://user-images.githubusercontent.com/694733/162698610-af20840e-b091-420b-a162-bab433b5a5a0.png">

**Additional context**

N.A.
