### ISSUE TITLE
Warning: Failed to upload artifact - 404

### ISSUE THREAD

**Issue by florian30491** [ncipollo/release-action#207]
**Describe the bug**

I am experiencing a problem with this action on a GitHub Enterprise server, see below the yml-file as a reference. 

```yml
on:
  workflow_dispatch:
    inputs:
      release-version-string:
        type: string
        required: true
  
jobs:
  publish-new-release:
    name: Publish new Release
    runs-on: [self-hosted, linux]
    permissions:
      contents: write
    #if: github.event.pull_request.merged == true # only merged pull requests must trigger this job
    steps:
      - uses: actions/checkout@v2
      
      - name: Push tag '${{ env.RELEASE_VERSION }}'
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ github.event.inputs.release-version-string }}
      
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_version }}
          artifacts: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
```

If I execute this action the release on the GitHub Enterprise Server will be created, but the release asset (README file) will not be uploaded to the server. In the log file I am getting the following warnings (errors). 

```log
Warning: Failed to upload artifact README.md. Error uploading to https://media.{hostname}/releases/223/files: 404. Retrying...
Warning: Failed to upload artifact README.md. Error uploading to https://media.{hostname}/releases/223/files: 404. Retrying...
Warning: Failed to upload artifact README.md. Error uploading to https://media.{hostname}/releases/223/files: 404. Retrying...
Warning: Failed to upload artifact README.md. Error uploading to https://media.{hostname}/releases/223/files: 404.
```
The `{hostname}` is a placeholder. 

See below the image of the created release.
![image](https://user-images.githubusercontent.com/58624223/166260024-594dffb0-45b4-462a-bf1b-0f5acdffeedb.png)

When I am using the same workflow and pass a different token e.g. `MY_TOKEN` (Personal Access Token of me) as a secret to the action then this action is working as expected.

**To Reproduce**

Unfortunately this bug cannot be reproduced on `github.com`. The support from GitHub asked me to file here an issue and to ask if a similar issue is already known here.

**Expected behavior**
The release will be created, and the README file will be uploaded as release asset.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 99.0.4844.74

**Additional context**

I hope you can provide me maybe more information that i can find a solution for my issue.
