### ISSUE TITLE
Release is not being updated

### ISSUE THREAD

**Issue by realnc** [ncipollo/release-action#210]
**Describe the bug**
When using this:

```yaml
allowUpdates: true
artifactErrorsFailBuild: true
body: 'Latest build'
generateReleaseNotes: false
name: 'Latest Build'
prerelease: true
replacesArtifacts: true
tag: latest_build
```

The release is not being updated. The tag still points to an older commit instead of the commit that triggered the job.

**To Reproduce**
Use this:
```yaml
allowUpdates: true
artifactErrorsFailBuild: true
body: 'Latest build'
generateReleaseNotes: false
name: 'Latest Build'
prerelease: true
replacesArtifacts: true
tag: latest_build
```

**Expected behavior**
The release should be updated to point to the commit that triggered the job. That means deleting the tag if it exists and recreating it.

**Desktop (please complete the following information):**
 - OS: Gentoo Linux
 - Browser Firefox
 - Version 100.0

**Additional context**
Example use case for how it should behave:

https://github.com/probonopd/linuxdeployqt/releases

The ` continuous` tag should point to the commit of that build.
