### ISSUE TITLE
Valid tag name results in "tag_name is not a valid tag"

### ISSUE THREAD

**Issue by EddieEldridge** [ncipollo/release-action#225]
**Describe the bug**
```json
Error: Error 422: Validation Failed: {"resource":"Release","code":"custom","field":"tag_name","message":"tag_name is not a valid tag"}, {"resource":"Release","code":"custom","message":"Published releases must have a valid tag"}, {"resource":"Release","code":"invalid","field":"target_commitish"}
```

```yaml
Run ncipollo/release-action@v1
  with:
    name: M[2](https://github.com/youneuoy/M2TWEOP-library/runs/7078219080?check_suite_focus=true#step:19:2)TWEOP-2.1.beta.[3](https://github.com/youneuoy/M2TWEOP-library/runs/7078219080?check_suite_focus=true#step:19:3)2
    tag: M2TWEOP-2.1.beta.32
    artifacts: M2TWEOP-2.1.beta.32.zip
    bodyFile: ./docs/releaseInfo/releaseDescription.md
    token: ***
    commit: testFeathures
    allowUpdates: true
    generateReleaseNotes: false
    omitBody: false
    omitBodyDuringUpdate: false
    omitDraftDuringUpdate: false
    omitName: false
    omitNameDuringUpdate: false
    omitPrereleaseDuringUpdate: false
    removeArtifacts: false
    replacesArtifacts: true
```
**To Reproduce**
Unknown

**Expected behavior**
[Here's a link to the run that had the issue](https://github.com/youneuoy/M2TWEOP-library/runs/7078219080?check_suite_focus=true)

What exactly is wrong here? The tag name is clearly set to `M2TWEOP-2.1.beta.32` and `M2TWEOP-2.1.beta.31` has worked before. I guess I'm just trying to understand what this message means exactly.

How exactly does this work? Do is it tag the repo and then make a release from that?
