### ISSUE TITLE
Upload failing

### ISSUE THREAD

**Issue by loiccoyle** [ncipollo/release-action#235]
I'm trying to use this action to upload the result of an action to a repository.

```
...
      - name: Upload images to loiccoyle/pi-gen
        uses: ncipollo/release-action@v1
        if: startsWith(github.event.inputs.repo_ref, 'refs/tags/')
        with:
          repo: pi-gen
          owner: loiccoyle
          token: ${{ secrets.ACCESS_TOKEN }}
          artifacts: deploy/*
          tag: ${{ github.event.inputs.repo_ref }}
```

The `deploy` directory contains 2 files, a small text file and a large disk img file roughly 800Mb in size.
The text file gets uploaded but the upload of the larger file fails with the following output:
```
Run ncipollo/release-action@v1
  with:
    repo: pi-gen
    owner: loiccoyle
    token: ***
    artifacts: deploy/*
    tag: refs/tags/test
    generateReleaseNotes: false
    omitBody: false
    omitBodyDuringUpdate: false
    omitDraftDuringUpdate: false
    omitName: false
    omitNameDuringUpdate: false
    omitPrereleaseDuringUpdate: false
    removeArtifacts: false
    replacesArtifacts: true
/home/pi/actions-runner/externals/node12/bin/node[7953]: ../src/env-inl.h:949:char* node::Environment::Allocate(size_t): Assertion `(ret) != (nullptr)' failed.
```

I can upload the disk img file manually with no issue though.

Any insight would be appreciated.
