### ISSUE TITLE
Getting Error 404 Not found while creating a release artifact

### ISSUE THREAD

**Issue by vinoopks** [ncipollo/release-action#24]
Hi,
I was getting an Error as **`'404: Not found'`** while creating a release artifact for a flutter project. I have built an apk file, but was unable to attach it to the tag due to this error. Path to the artifact  seems to be fine. Am I missing something here?

```
- name: Push APK to Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/debug/*.apk"
        token: ${{ secrets.TOKEN }}

```
![image](https://user-images.githubusercontent.com/33143132/94891866-da60fd80-04a0-11eb-9e8d-dd5ae8d60694.png)
