### ISSUE TITLE
Scheduled releases without pushing any tag

### ISSUE THREAD

**Issue by eggplants** [ncipollo/release-action#25]
Is it possible?

```yml
name: Schedule releases

on: 
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Tagname
        run: echo "DATE=$(date +%y%m%d)" >> $GITHUB_ENV
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release.tar.gz,foo/*.txt"
          tag: day${{ env.DATE }}
          token: ${{ secrets.GITHUB_TOKEN }}
```
