### ISSUE TITLE
Created release doesn't contain workflow update

### ISSUE THREAD

**Issue by avoca999** [ncipollo/release-action#252]
Hello - I assume I'm doing something wrong here, but I can't see what.

My workflow takes a release number, updates a version.txt, and creates a tag and release named after the passed-in release number.

However, the released zip includes the **previous** version of the version.txt file. The updated version isn't tagged with the new tag.

A workflow snippet is:

```
    steps:
    - name: Check out
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 
        # so it gets tags
    
    - name: Update version
      uses: DamianReeves/write-file-action@master
      with:
        path: '${{ github.workspace }}/version.txt'
        write-mode: overwrite
        contents: ${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}
    
    - name: Commit & Push
      uses: Andro999b/push@v1.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
        force: true
        message: 'Overwritten by create-cp-release - ${{ github.date }}'
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
          tag_name: ${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}
          release_name: ${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }} - ${{ github.event.inputs.description }}
          draft: false
          prerelease: false
```
This updates version.txt OK, but it doesn't have the new tag:
![image](https://user-images.githubusercontent.com/32246338/189677614-8f33136b-a60f-4afc-82ef-ce3157e1f83a.png)

Am I missing something in the call to create-release that is not tagging the changes made in this workflow with the new tag?

Any help gratefully received!
