### ISSUE TITLE
Will you update the action to use Node.js 16

### ISSUE THREAD

**Issue by ecrasy** [ncipollo/release-action#265]
**Is your feature request related to a problem? Please describe.**
Got the warning from git actions:
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16

**Describe the solution you'd like**
Will you please update the action to use Node.js 16 ?

**Comment by ncipollo** [comment]
Pretty sure this has already been fixed, see #256. Make sure you are using the latest version (or v1).

**Comment by StefanLobbenmeierObjego** [comment]
> (or v1)

we still get this warning when using @v1:


```yml
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
```
