### ISSUE TITLE
Error 422: Validation Failed: `{"resource":"Release","code":"already_exists","field":"tag_name"}`

### ISSUE THREAD

**Issue by itsankit-google** [ncipollo/release-action#267]
**Is your feature request related to a problem? Please describe.**
If the tag and release already exists the action fails.
Is there a way to just ignore updating the release if the action fails?
Here, is the configuration of my action:-
```
Run ncipollo/release-action@58ae73b360456532aafd58ee170c045abbeaee37
  with:
    allowUpdates: false
    prerelease: false
    artifactErrorsFailBuild: true
    removeArtifacts: false
    replacesArtifacts: false
    token: ***
    tag: <tag_name>
    body: <body>
    artifacts: <artifact_path>
```

**Describe the solution you'd like**
We don't want the action to fail the workflow but just omit overwriting the release.

**Describe alternatives you've considered**
Considered skipping the action completely if the tag/release exists but cannot find any git command 
or any other suitable way to do it in github actions workflow since we want to publish the release the first time if it does not exists.

**Additional context**

**Comment by itsankit-google** [comment]
I tried to workaround it like this with `allowUpdates=true` because ultimately I do not want the release assets to be replaced.

```
Run ncipollo/release-action@58ae73b360456532aafd58ee170c045abbeaee37
  with:
    allowUpdates: true
    prerelease: false
    artifactErrorsFailBuild: true
    removeArtifacts: false
    replacesArtifacts: false
    token: ***
    tag: <tag_name>
    body: <body>
    artifacts: <artifact_path>
```
But it fails with error instead of omitting it.
```
Error: Error undefined: Failed to upload artifact cdap-sandbox-6.7.2.zip. Validation Failed: {"resource":"ReleaseAsset","code":"already_exists","field":"name"}.
```
