### ISSUE TITLE
Artifacts should be a list or dictionary

### ISSUE THREAD

**Issue by Bilge** [ncipollo/release-action#271]
**Is your feature request related to a problem? Please describe.**
Using a comma delimiter precludes uploading artefacts containing commas in their filenames.

**Describe the solution you'd like**
The artefact list should be an actual list, or better yet, a dictionary that allows renaming.

<table>
<thead>
<tr><td>Before</td><td>After</td></tr>
</thead>
<tr>
<td>

```yaml
with:
  artifacts: "release.tar.gz,foo/*.txt"
```

</td>
<td>

```yaml
with:
  artifacts:
    - release.tar.gz
    - foo/*.txt
```

</td>
</tr>
</table>

Moreover, by accepting a dictionary too, we could use the key names to implicitly rename the release.

```yaml
with:
  artifacts:
    My Product v1.0.tar.gz: release.tar.gz
```
