### ISSUE TITLE
artifacts input cannot find patterm

### ISSUE THREAD

**Issue by Roms1383** [ncipollo/release-action#302]
**Describe the bug**

I don't get why my files are not added to release as assumed,
when I define, e.g. :
```yaml
      # ...
      - name: Create release ${{ github.ref_name }}
        uses: ncipollo/release-action@v1
        with:
          # the paths here are supposed to be correct, aren't they ?
          artifacts: "Addicted-ubuntu-latest-${{ github.ref_name }}.zip,Addicted-windows-latest-${{ github.ref_name }}.zip"
          # mostly unrelated, but in case
          draft: ${{ startsWith(github.ref_name, 'beta') || startsWith(github.ref_name, 'alpha') }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifactErrorsFailBuild: true
```
The Github Action fails, see screenshot below.

**To Reproduce**
Not sure, maybe this is because filename contains a lot of dots ?

**Expected behavior**
I would expect my files to be added to the final releases.

**Screenshots**
<img width="1512" alt="Screenshot 2566-01-26 at 10 18 28" src="https://user-images.githubusercontent.com/21016014/214751762-eb767606-a9e6-4d65-bf2a-0620c2669c36.png">

**Additional context**
Ran on `ubuntu-latest`.
