### ISSUE TITLE
Artifact pattern did not match any files

### ISSUE THREAD

**Issue by samsmithnz** [ncipollo/release-action#307]
**Describe the bug**
I can't find artifacts. I'm specifying the exact path, and it's still not found. Showing details with a run command and the release with full paths.

![image](https://user-images.githubusercontent.com/8389039/217077245-64a11650-e46d-499d-a826-4308a5a588bd.png)

**To Reproduce**
My YAML is similar to this (stripped out irrelevant steps)
```
  release:
    runs-on: ubuntu-latest
    needs: 
    - build
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3.0.2
      with:
        name: drop 
        path: drop 
    - run: dir ${{ github.workspace }}/drop/*.*
    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        tag: ${{ needs.build.outputs.Version }}
        name: Release ${{ needs.build.outputs.Version }}
        token: ${{ secrets.GITHUB_TOKEN }} 
        artifacts: "${{ github.workspace }}/drop/PuzzleSolver.dll"
```

**Expected behavior**
I've tried using *.*, *, just the directory, using the latest action (I was using `@v1` for most testing), and now exact and full paths to the files, but still it can't find the files. What am I missing?

Also unclear about why there are two variations of the same error message.
