### ISSUE TITLE
After releasing minor version no new releases are created anymore

### ISSUE THREAD

**Issue by mstenz** [ncipollo/release-action#308]
**Describe the bug**
I have created a test repo extra for this. everything worked fine for releasing pre-releases and they are shown by github. Then after i did a minor release (bumped from 0.0.64 to 0.1.0 even when the pipeline is runnig without any error it does not create a release on the github release page.

**To Reproduce**
This is my configuration for release:

```
      - name: Upload as pre-release 
        id: uploadAsPreRelease
        uses: ncipollo/release-action@v1.12.0
        with:
          prerelease: true
          tag: pre-${{ needs.build.outputs.version }}
          name: Automatic build from main pre-${{ needs.build.outputs.version }}
          body: xxxxxxx
          generateReleaseNotes: true
          commit: ${{ needs.build.outputs.commit }}
          token: ${{ secrets.GITHUB_TOKEN }}
```

this is my configuration for release:

```      - name: Create release entry on GitHub
        id: uploadAsRelease
        uses: ncipollo/release-action@v1.12.0
        with:
          prerelease: false
          tag: ${{ needs.build.outputs.version_tag }}
          commit: ${{ needs.build.outputs.commit }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
```

**Expected behavior**
releases are visible as exepcted

**Additional context**
somehow i have the feeling that internally in github the release still exist, it is just not shown. But i am not sure on this. Because the Tag itself is created, but not shown when going to Tags on release page.
