### ISSUE TITLE
Help with updating an existing tag/release

### ISSUE THREAD

**Issue by proddy** [ncipollo/release-action#31]
First thanks for sharing the Action. It's the best one I've found so far.

I have a particular need but can't for the life of me get it to work. Basically, I want to update a release that has a fixed tag with the latest content of the repo, from a particular branch. What's happening is that the release assets's Source Code always contains the old source files although the branch has been updated. If that makes any sense at all?

The use case for example is to create a nightly-build from the `dev` branch. Or on demand.

My action script is:
```yaml
name: Build v3 Firmware - dev branch

on:
  push:
    branches:
    - "dev"
    paths:
    - 'CHANGELOG_LATEST.md'
    - './src/version.h'
  workflow_dispatch:
    branches: [ dev ]

jobs:
        
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev
          
      - name: Version
        id: fetch_version
        run: |
             version=`grep -E '^#define EMSESP_APP_VERSION' ./src/version.h | awk '{print $3}' | sed 's/"//g'`
             echo "::set-output name=s::$version"
      - name: Changelog
        run: cat CHANGELOG_DEV.md > BODY.md
               
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          name: dev build v${{steps.fetch_version.outputs.s}}
          tag: dev
          prerelease: true
          allowUpdates: true
          artifacts: "*.ini"
          bodyFile: "BODY.md"
          token: ${{ secrets.GITHUB_TOKEN }}
```

I'm probably doing something wrong and should do a `commit` or `tag` action first?

https://github.com/proddy/CI_TEST/blob/v3/.github/workflows/build_v3_firmware.yml
