### ISSUE TITLE
Update Release

### ISSUE THREAD

**Issue by heliomarpm** [ncipollo/release-action#314]
Hello,
Could you please point me to a way to update the release?

My script runs with matrix.os and in this way 3 release publications are created, I would just like to update in case it already exists, is there a way to do this?

Thanks

Example of my script
```yml
name: build/release
on:
   push:
     tags: ["*"]

jobs:
   build_release:
     if: startsWith(github.ref, 'refs/tags/v')
     runs-on: ${{ matrix.os }}
     permissions:
       contents: write
    
     strategy:
       matrix:
         os: [ubuntu-latest, macos-latest, windows-latest]

     steps:
       - name: checkout
         uses: actions/checkout@v3

       - name: Install Node.js, NPM and Yarn
         ....

       - name: Build Electron app
         ....
      
       - name: Create Release Asset
         uses: ncipollo/release-action@v1
         with:
           draft: true
           prerelease: false
           generateReleaseNotes: true
           artifacts: |
             ./dist/latest*.yml
             ./dist/*.dmg
             ./dist/*.zip
             ./dist/*.AppImage
             ./dist/*.deb
             ./dist/*.freebsb
             ./dist/*.rpm
             ./dist/*.exe
```
