### ISSUE TITLE
Action not adding artifact to release data

### ISSUE THREAD

**Issue by RicardoMonteiroSimoes** [ncipollo/release-action#32]
**Describe the bug**
I'm compiling LaTeX and using your action to get the artifact and then generate a release. The release is generated without a problem, but the artifact is never uploaded

**To Reproduce**
My yaml configuration for your action is the following:
```yaml
      - uses: ncipollo/release-action@v1
        with:
          artifacts: main_v${{ needs.create_new_release_tag.outputs.new-tag }}
          tag: "${{ needs.create_new_release_tag.outputs.new-tag }}"
          commit: main
          body: "New Release of documentation"
          token: ${{ secrets.AUTO_RELEASE_TOKEN }}
```

The Artifact looks like this after being uploaded:
![image](https://user-images.githubusercontent.com/30594398/110869066-fe373380-82c9-11eb-9332-874c01ff52df.png)

The release itself only contains the source, but not the `main_v0.0.1` in this case

**Expected behavior**
The file `main_v0.0.1` should be inserted into the newest release

**Screenshots**

**Desktop (please complete the following information):**
 - GitHub Action
