### ISSUE TITLE
Missing "body.md" with "generateReleaseNotes: true"

### ISSUE THREAD

**Issue by jwalton** [ncipollo/release-action#325]
**Describe the bug**

Just tried out your action with `generateReleaseNotes: true`, but it failed with the error:

```txt
Error: Error undefined: ENOENT: no such file or directory, open 'body.md'
```

**To Reproduce**

Configuration is:

```yaml
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          makeLatest: true
          artifacts: "rust-book-abridged.pdf"
          bodyFile: "body.md"
```

Action [run is here](https://github.com/jwalton/rust-book-abridged/actions/runs/4820197122/jobs/8584383611) and the [full config is here](https://github.com/jwalton/rust-book-abridged/blob/76cb57b25abfe5ed6e6cfce12ce1a43c098a89da/.github/workflows/deploy-gh-pages.yml#L85-L90).

**Expected behavior**
Action should generate release notes.
