### ISSUE TITLE
How to fix "tag_name is not a valid tag"？

### ISSUE THREAD

**Issue by TheMelody** [ncipollo/release-action#335]
```
Error 422: Validation Failed: {"resource":"Release","code":"custom","field":"tag_name","message":"tag_name is not a valid tag"}, {"resource":"Release","code":"custom","message":"Published releases must have a valid tag"}, {"resource":"Release","code":"invalid","field":"target_commitish"}
```

yml：
```
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "app/build/outputs/apk/release/*.apk"
          artifactErrorsFailBuild: true
          body:  |
            **demo**
          token: ${{ secrets.github_token }}
          commit: master
          tag: ${{ github.ref_name }}
```
