### ISSUE TITLE
Updating a release updates artifacts, but keeps the `Source code` assets

### ISSUE THREAD

**Issue by ttytm** [ncipollo/release-action#368]
**Describe the bug**
Updating a release via a github action, updates artifacts, but keeps the `Source code` assets.

**To Reproduce**
Make a release that updates an existent tag.

**Expected behavior**
`Source code` assets are updated when the release is updated.

It might be for the reason that the initial commit stays the same. I tried adding a `commit` value to get the commit updated, but it stays the same.

**Screenshots**
> ![Screenshot_20230912_022627](https://github.com/ncipollo/release-action/assets/34311583/853cec02-a377-4911-93d2-6c6ee01776e1)

```
Run ncipollo/release-action@v1
  with:
    artifacts: webui-linux-clang-debug-x64.tar.gz
    allowUpdates: true
    prerelease: true
    commit: 2f1f852959f15700d1134fe48c4d62e0b1d6c97d
    tag: nightly
    body: 'Generated on <samp>2023-09-12 00:20:07 UTC</samp> from commit 2f1f852959f15700d1134fe48c4d62e0b1d6c97d.'
    name: WebUI Development Build
    generateReleaseNotes: false
    makeLatest: legacy
    omitBody: false
    omitBodyDuringUpdate: false
    omitDraftDuringUpdate: false
    omitName: false
    omitNameDuringUpdate: false
    omitPrereleaseDuringUpdate: false
    removeArtifacts: false
    replacesArtifacts: true
    skipIfReleaseExists: false
    token: ***
    updateOnlyUnreleased: false
```

**Additional Context**

A possible solution could be to push / updated commits for the specified tag ("nightly" in the example above and below). 

I'd like to achieve the same release style for nightly releases as kovid goyal does for kitty. An updating nighlty release that doesn't create announcement noice.
- https://github.com/kovidgoyal/kitty/releases
- https://github.com/kovidgoyal/kitty/blob/master/publish.py
- https://github.com/kovidgoyal/kitty/tree/nightly

PS: Thanks for the work on that action!
