### ISSUE TITLE
Artifact is not working on wondows runner

### ISSUE THREAD

**Issue by ouaibsky** [ncipollo/release-action#392]
**Describe the bug**
Try to release some msi files build on a windows runner, but nothing is included with a regex like here under.
It works very well on ubuntu and macos.

 ```yml
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./target/*.msi"

```

Thx for help
Christophe
