### ISSUE TITLE
Getting "Error undefined: No tag found in ref or input!" when running on a release:published trigger

### ISSUE THREAD

**Issue by richbrowne-openfin** [ncipollo/release-action#393]
I'm using v1.13.0, and am getting a "Error: Error undefined: No tag found in ref or input!" error when running using a release:published trigger. According to the [GitHub docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release), the `GITHUB_REF` value will be "Tag ref of release refs/tags/<tag_name>" so this error should not be occurring?

To confirm, my workflow trigger is set to:

```
on:
  release:
    types: [published]
```

My ncipollo/release-action workflow task:

```
      - name: Update release
        uses: ncipollo/release-action@v1.13.0
        with:
          allowUpdates: ${{ true }}
          bodyFile: metadata/${{ needs.adapter.outputs.version }}.md
          name: v${{ needs.adapter.outputs.version }}
          omitNameDuringUpdate: ${{ true }}
          omitPrereleaseDuringUpdate: ${{ true }}
          token: ${{ secrets.GITHUB_TOKEN }}
```
