### ISSUE TITLE
[Feature request] Generate sha256 from source tarballs

### ISSUE THREAD

**Issue by CarterLi** [ncipollo/release-action#400]
**Is your feature request related to a problem? Please describe.**
A lot of package managers [requires](https://github.com/CarterLi/MINGW-packages/blob/master/mingw-w64-fastfetch/PKGBUILD#L22) [sha256sum](https://github.com/Homebrew/homebrew-core/blob/master/Formula/f/fastfetch.rb#L5) to update the build scripts.

I succeeded in generating sha256sum of artifacts with (take my project as an example)

```yaml
- name: generate sha256sum
  run: |
    sha256sum fastfetch-*/* > fastfetch-sha256sum.txt

- name: create release
  uses: ncipollo/release-action@v1
  with:
    bodyFile: fastfetch-sha256sum.txt
    tag: 2.4.0
```

However I can't do that for source tarballs, because the tag hasn't been created yet.

```
wget https://github.com/fastfetch-cli/fastfetch/archive/refs/tags/2.4.0.tar.gz # 404
```

So that every time I want to update the build script of 3rd party package managers, I have to download the tarball manually; run `sha256sum`; delete the tarball.

**Describe the solution you'd like**

Since the tag is generated by `ncipollo/release-action`, it should be able to fetch the tarball file, and generate some text with it.

**Describe alternatives you've considered**

An optional `run` section that runs after new tag is created. So users can do something with the tag

**Additional context**
