### ISSUE TITLE
Generated What's Changed doesn't contain all the commits

### ISSUE THREAD

**Issue by marcossv9** [ncipollo/release-action#422]
**Describe the bug**
The Generated What's Changed doesn't contain all the commits, but the diff shows that all the commits have been included in the release. Only the `What's changed` is wrong.

**To Reproduce**

I have a reusable workflow that uses the action to create a release when a tag is pushed:

```
#
# Description: This workflow will create a new release when a tag is pushed to the repository.
#

name: Create Release

on:
  workflow_call:

permissions:
  contents: read
  id-token: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    environment: operations
    steps:
      - name: Generate Githup App Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: my-app-id
          private-key: my-private-key
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          ref: ${{ github.ref }}
          token: ${{ steps.generate-token.outputs.token }}
      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          token: ${{ steps.generate-token.outputs.token }}
```
Actual workflow that calls the reusable one:

```
#
# Description: This workflow will create a new release when a tag is pushed to the repository.
#

name: Create Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: read
  id-token: write

jobs:
  create-release:
    name: Create Release
    secrets: inherit
    uses: org/repo/.github/workflows/_create-release.yaml@main
```

**Expected behavior**
A changelog for the release that contains all the changes (commits) that happened between the last release and the new one.
**I see 6 commits in the diff, but then the what's changed only shows 4 commits...**

**Screenshots**
Changelog:
![changelog](https://github.com/ncipollo/release-action/assets/12616390/4066ef2f-816f-48ef-94e4-0f6e5b0c06be)
Diff:
![diff](https://github.com/ncipollo/release-action/assets/12616390/f54bfbb2-63e3-4a2c-b384-90a097d553c8)
