### ISSUE TITLE
Getting 404 response for artifacts if I specify tag.

### ISSUE THREAD

**Issue by schmidtw** [ncipollo/release-action#43]
**Release succeeds, but released files are not available/404**

It appears that when I add the tag field like how I think you have it documented, the files are "uploaded" and everything looks amazing, but when I try to download them they aren't really there.

**To Reproduce**
This is the configuration I used that caused the problem:
```
      - name: create release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: ${{ steps.prep.outputs.rname }}
          draft: false
          prerelease: false
          bodyFile: ${{ steps.prep.outputs.body }}
          artifacts: "artifacts/*"
          token: ${{ secrets.GITHUB_TOKEN }} 
```

When I remove the `tag` field, the files are uploaded & all goes to plan.

This works great:
```
      - name: create release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.prep.outputs.rname }}
          draft: false
          prerelease: false
          bodyFile: ${{ steps.prep.outputs.body }}
          artifacts: "artifacts/*"
          token: ${{ secrets.GITHUB_TOKEN }} 
```

**Expected behavior**
Either the documentation needs to be updated or there is a bug in the tag handling code.
