### ISSUE TITLE
Release notes are not auto generated if we are updating the release

### ISSUE THREAD

**Issue by nicola-lunghi** [ncipollo/release-action#432]
```
  - name: Create Release
        uses: actions-ext/ncipollo-release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "kakao-2x100g-net-linux_${{ env.COMP_VERSION }}.tar.gz,README.md"
          draft: true
          generateReleaseNotes: true
          omitDraftDuringUpdate: false
          removeArtifacts: true
          updateOnlyUnreleased: true
```

If I rerun this job and try to update the draft release, the release notes are not auto generated anymore.
In the description I get only the release name and not the changelog.
If the release doesn't exist I get the release notes as it is supposed to be.

Normal release page:
![image](https://github.com/ncipollo/release-action/assets/25422924/363b20e1-60a2-4c74-b2bc-11cbfcc838c5)
