### ISSUE TITLE
Fail to publish to release

### ISSUE THREAD

**Issue by yanecc** [ncipollo/release-action#443]
**Describe the bug**

I want to use this action to add compiled products after a new release. My current setup is as follows.

```
  - name: Publish to Releases
    uses: ncipollo/release-action@v1
    with:
      name: "MockGPT v${{ github.event.release.tag_name }}"
      allowUpdates: true
      artifactErrorsFailBuild: false
      artifacts: "${{ steps.get_name.outputs.BSD_AMD }}.tgz,${{ steps.get_name.outputs.LINUX_ARM }}.tgz,${{ steps.get_name.outputs.LINUX_AMD }}.tgz,${{ steps.get_name.outputs.WIN_AMD }}.zip,${{ steps.get_name.outputs.MAC_NAME }}.tgz"
      omitNameDuringUpdate: true
      omitBodyDuringUpdate: true
      omitPrereleaseDuringUpdate: true
```

https://github.com/yanecc/MockGPT/actions/runs/8951721844/job/24588443962#step:8:23

```
Error: Error 403: Resource not accessible by integration
```
