### ISSUE TITLE
Release notes disappear when updating an existing release to latest

### ISSUE THREAD

**Issue by ataylormays-duetto** [ncipollo/release-action#462]
**Describe the bug**
We use this action to first create a pre-release when code is deployed to a pre-prod environment, then to update that same release to mark it as latest once the code is deployed to pre-prod. During the first step we generate release notes, but I've found that during the second step the release notes are removed.

**To Reproduce**
We use the following when code is released to a pre-prod environment:
```
- uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          prerelease: true
          tag: ${{ steps.maven_version.outputs.version }}
```

And the following when code is released to production:
```
- uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          generateReleaseNotes: true
          makeLatest: true
          tag: ${{ inputs.VERSION }}
          updateOnlyUnreleased: true
```

**Expected behavior**
The second action above is intended to only update the release to latest and do nothing more. Instead the release notes that were previously on the pre-release disappear.

**Comment by ncipollo** [comment]
Try removing the generate release notes from the second action. GitHub tried to diff to the current release from the previous one and I'm guessing it's seeing no diff in this scenario.


In any case, this is being generated via GitHub, so it's not likely something we can control within the action.

**Comment by ataylormays-duetto** [comment]
I'd originally implemented this flow without the `generateReleaseNotes: true` in the second action, and that's when I originally noticed the release notes were disappearing. I tried adding `generateReleaseNotes: true` to solve it but it didn't.

There are diffs between the release I'm modifying and the prior release - that's why it has release notes when I call the action originally. The second action is intended to only update the release by marking it as latest, but everything else about the release should be preserved, including the release notes.

For example, I might have version `1.0.0` running in production and is the latest GH release. Once I release version `1.0.1` to pre-prod, I create a GH release and it contains the release notes for the diffs between `1.0.0` and `1.0.1`, and this GH release is marked as "pre-release". Once it's released to production, I want to mark `1.0.1` as "latest", but it should still contain the release notes showing the diffs between `1.0.0` and `1.0.1`. Is this possible with this action?

**Comment by ncipollo** [comment]
It wouldn't be a limitation of the action, this is GitHub itself generating release notes. We just pass in an option to the release endpoint to tell it to auto-generate the release notes. Unless there is some new option on the API I don't think there is really anything the action can do here.

Your other option is to just create the release notes yourself, then you can attach them as the body.

**Comment by ataylormays-duetto** [comment]
Hm ok. Let me maybe ask the question slightly differently - is there a way to use this action to update an existing release by _only_ setting it to latest and not update anything else about the release?

**Comment by ncipollo** [comment]
You should be able to remove that generate release notes option and set omitBody to true so it won't try and set a blank body. Then set whatever else you want to true.

Please see read me for list of optionsz.

**Comment by ataylormays-duetto** [comment]
Aha, I didn't realize the significance of `omitBody` - that fix worked! The following is now behaving as expected.

```
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitBody: true
          makeLatest: true
          tag: ${{ inputs.VERSION }}
          updateOnlyUnreleased: true
```

Thanks @ncipollo!
