### ISSUE TITLE
Pattern of artifacts is understood as folder

### ISSUE THREAD

**Issue by Lecrapouille** [ncipollo/release-action#485]
**Describe the bug**

The pattern of the artifacts is understood as folder

**Steps to reproduce**

```
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.workspace }}/artifacts/*.tar.gz"
          allowUpdates: true
          makeLatest: true
```

Produce the following logs:

```
Warning: Artifact is a directory:/home/runner/work/gdcef/gdcef/artifacts/gdCEF-0.14.0_Godot-4.3_macOS_ARM64.tar.gz/. Directories can not be uploaded to a release.
Warning: Artifact is a directory:/home/runner/work/gdcef/gdcef/artifacts/gdCEF-0.14.0_Godot-4.3_Windows_X64.tar.gz/. Directories can not be uploaded to a release.
Warning: Artifact is a directory:/home/runner/work/gdcef/gdcef/artifacts/gdCEF-0.14.0_Godot-4.3_Linux_X64.tar.gz/. Directories can not be uploaded to a release.
```

While the previous CI rules placed files on the correct location. 

```
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: "*.tar.gz"
          path: artifacts
```

See the log:

```
Run actions/download-artifact@v4
Found 3 artifact(s)
Filtering artifacts by pattern '*.tar.gz'
Preparing to download the following artifacts:
- gdCEF-0.14.0_Godot-4.3_Windows_X64.tar.gz (ID: 2287315750, Size: 139941980)
- gdCEF-0.14.0_Godot-4.3_Linux_X64.tar.gz (ID: 2287308781, Size: 382098615)
- gdCEF-0.14.0_Godot-4.3_macOS_ARM64.tar.gz (ID: 2287290739, Size: 111566119)
Redirecting to blob download url: https://productionresultssa0.blob.core.windows.net/actions-results/2ab6953b-dd79-46e5-ae77-d38b923b4814/workflow-job-run-3c1dd1d3-ee81-5ae5-6423-e8b93be79bee/artifacts/6f13fe488ecbb2041ffea780b64d2b8f23c5f6e3e4a7fd65766fe068ac234581.zip
Starting download of artifact to: /home/runner/work/gdcef/gdcef/artifacts/gdCEF-0.14.0_Godot-4.3_Windows_X64.tar.gz
...
```

See ci file
[ci.yml.txt](https://github.com/user-attachments/files/18045299/ci.yml.txt)

**Comment by ncipollo** [comment]
Hmm that's weird. It looks like the glob is resolve those tarballs as directories (see the ending slash). Are you sure those aren't actually directories?

**Comment by Lecrapouille** [comment]
@ncipollo I'm adding extra "ls -la" to check if they are not folders. Waiting the end of the CI ...

**Comment by ncipollo** [comment]
Thanks for taking a look! I think this has come up before and I _think_ that download action you are using is also extracting the tarballs after they download.

**Comment by Lecrapouille** [comment]
Arf I forget an " in my ls I have to redo and wait 15 min.

I think I understood the issue: i'm using actions/upload-artifact + actions/download-artifact + ncipollo/release-action because I using 3 OS so I need to store them on a common place and then get push to release page.  actions/upload-artifact force to use zip and the name was hidden. Artifacts are real archive but zip holding tar.gz.

```
      - name: Upload artifact
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          compression-level: 0
          name: ${{ steps.archive.outputs.tarball_name }}
          path: ${{ steps.archive.outputs.tarball_name }}
```

I'll give a try directly using your release action directly even in matrix my tarball have unique name I guess
