### ISSUE TITLE
Action failing with "Error: Error undefined: releases.find is not a function"

### ISSUE THREAD

**Issue by mnsrulz** [ncipollo/release-action#489]
**Describe the bug**
With very simple configuration including assets and tag name, the action intermittently fail with the error message "Error undefined: releases.find is not a function". Rerunning the step solves the issue intermittently. Is there a way to get what's going on behind the scenes to get more details about the root cause of the failure?

**To Reproduce**
Use the sample workflow below

**Expected behavior**
The workflow should run without any error

**Screenshots**
![image](https://github.com/user-attachments/assets/083c694e-7a4a-406e-bde6-af53799c56e9)

**Additional context**
Workflow file

```
  release-rolling-data:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   
          ref: main        
      - name: Download snapshot images Artifact
        uses: actions/download-artifact@v4
        with:
          name: rolling-data
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "temp/*.parquet"
          tag: sometagvalue
          commit: "main"
          allowUpdates: "true"
```
