### ISSUE TITLE
Artifacts are uploaded after the GH Release `published` event is triggered

### ISSUE THREAD

**Issue by carlosperate** [ncipollo/release-action#501]
When creating a GH Release with files to upload as artifacts, the GH Release is published before the file uploads are done.

This means that any workflow triggered from a GH Release being "published", will start running before all the artifacts are availble in the release. 

```yaml
on:
  release:
    types: published

jobs:
  download-release-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Set the GH Release tag to step output
        id: get_tag
        shell: bash
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      # At this point the GH release artifacts might not have been completely uploaded by ncipollo/release-action
      - name: Download GH Release artifacts
        shell: bash
        run: gh release download ${{ steps.get_tag.outputs.tag }} --repo ${{ github.server_url }}/${{ github.repository }}
        env:
          GH_TOKEN: ${{ github.token }}
```
