### ISSUE TITLE
Can this action override an existing tag?

### ISSUE THREAD

**Issue by thibaultcha** [ncipollo/release-action#503]
In [our repository](https://github.com/Kong/ngx_wasm_module) we use this action to release a new "nightly" build periodically. The `nightly` git tag needs to be overridden every time a new nightly release is build (from our main branch) and it needs to point to the latest commit on `main`. We currently use this action like so:

```yml
        with:
          prerelease: true
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
          generateReleaseNotes: true
          name: ${{ needs.setup.outputs.release_name }} # nightly-YYYYMMDD
          tag: nightly
```

But we notice the `nightly` tag is not being updated and still points to an older commit.

Do we need to also specify `commit` to make this work? It isn't clear from the documentation and this action only runs once a week, so I thought I'd ask and make the update later this week for the next time it runs.

Thank you!
