### ISSUE TITLE
Cannot add artifacts to release

### ISSUE THREAD

**Issue by wirehack7** [ncipollo/release-action#515]
**Describe the bug**
Currently I am unable to add artifacts to a release with this action:
`::error::Error undefined: Failed to upload artifact extension.zip. Could not determine name of attachment..`

**To Reproduce**
I'm using following action (on Gitea):
And yes, github. variables are working on Gitea

```yaml
name: Create Chrome Extension Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get previous tag
        id: get_previous_tag
        run: |
          git fetch --tags
          CURRENT_TAG="${GITHUB_REF##*/}"
          PREV_TAG=$(git tag --sort=-creatordate | grep -v "^$CURRENT_TAG$" | head -n 1 || true)

          if [ -z "$PREV_TAG" ]; then
            echo "No previous tag found. Will generate changelog from initial commit."
          else
            echo "Found previous tag: $PREV_TAG"
          fi

          echo "previous_tag=$PREV_TAG" >> "$GITHUB_OUTPUT"

      - name: Generate changelog
        id: changelog
        run: |
          echo "🚀 New version ${{ gitea.ref_name }}:" > changelog.txt
          echo "Changelog since ${{ steps.get_previous_tag.outputs.previous_tag }}:" >> changelog.txt
          if [ -n "${{ steps.get_previous_tag.outputs.previous_tag }}" ]; then
            echo "Changelog since ${{ steps.get_previous_tag.outputs.previous_tag }}:" >> changelog.txt
            git log ${{ steps.get_previous_tag.outputs.previous_tag }}..HEAD --pretty=format:"- %s (%an)" >> changelog.txt
          else
            git log --pretty=format:"- %s (%an)" >> changelog.txt
          fi

      - name: Create archive
        run: |
          cd source
          zip -r "../extension.zip" .
          cd ..

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITEATOKEN }}
          name: Release ${{ github.ref_name }}
          bodyFile: changelog.txt
          artifacts: "extension.zip"
          artifactContentType: application/zip
          draft: false
          prerelease: false
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
```

extension.zip is being created, but I don't understand the "cannot get name" error.

**Expected behavior**
Artifact added to release
