### ISSUE TITLE
Error uploading artifact "EISDIR: illegal operation on a directory, read."

### ISSUE THREAD

**Issue by robpc** [ncipollo/release-action#53]
**Describe the bug**
When I create a release using the `artifacts` parameter, the file does not get added to the release and reports the following error for each one:

```
Failed to upload artifact [filename]. EISDIR: illegal operation on a directory, read. 
```

**To Reproduce**
My build can be seen [here](https://github.com/robpc/maze-test-game/blob/3c3e1d46f385c5f8c37670ff78ca7592d3ec504e/.github/workflows/release-macos.yml). Not sure if it is specific to using `actions/upload-artifact`, the job itself is fairly simple:

```yaml
  release:
    runs-on: ubuntu-latest
    needs:
      - exports
      - exports-macos
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: build/
      - run: |
          version=${GITHUB_REF/refs\/tags\/v/}
          echo "version=${version}" >> $GITHUB_ENV
      - uses: ncipollo/release-action@v1
        with:
          name: Release v${{env.version}}
          tag: ${{env.version}}
          draft: true # for testing
          allowUpdates: true
          artifacts: build/*.zip
          token: ${{ secrets.GITHUB_TOKEN }}
```

**Expected behavior**
File added to the release

**Screenshots**
[Example Github Workflow run](https://github.com/robpc/maze-test-game/runs/2638806579?check_suite_focus=true)
<img width="730" alt="release-error" src="https://user-images.githubusercontent.com/3671561/119131811-ef76a680-ba07-11eb-831d-3baf1e87fffe.png">
