### ISSUE TITLE
Name cannot contain variable

### ISSUE THREAD

**Issue by ari** [ncipollo/release-action#63]
When putting a variable into the name like this, github throws an error.

```
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          name: onCourse ${{ env.VERSION }}
          artifacts: "server/build/distributions/onCourseServer-*.zip", "server/build/distributions/onCourseServer-*.sha256"
          body: "See release notes here https://www.ish.com.au/onCourse/doc/release-notes/${{ env.VERSION }}/release-notes.html"
          token: ${{ secrets.GITHUB_TOKEN }}
```

https://github.com/ishgroup/oncourse/actions/runs/945003848/workflow
