### ISSUE TITLE
The action sometimes creates draft when explicitly said don't

### ISSUE THREAD

**Issue by Anthonyive** [ncipollo/release-action#65]
**Describe the bug**
The action sometimes creates draft when explicitly said don't.

**To Reproduce**
I have set up a workflow where it checks if a tag exists. If the tag already exists, it will delete the tag and release first, then uses this action to recreate another.

**Expected behavior**
I expect it to create releases instead of drafts.

**Screenshots**

![Screen Shot 2021-06-26 at 4 00 16 PM](https://user-images.githubusercontent.com/8257285/123527841-b4ffc980-d697-11eb-9d6f-2a33fd3b0fd8.png)
*No release here*

![Screen Shot 2021-06-26 at 4 00 33 PM](https://user-images.githubusercontent.com/8257285/123527843-b6c98d00-d697-11eb-875b-4ab4301f64e0.png)
*It shows as draft*

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 14.1.1

**Additional context**

<details>
<summary>main.yml</summary>

```yml
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # compile tex file
      - name: LaTeX Action
        uses: xu-cheng/latex-action@v2
        with:
          # The root LaTeX file to be compiled
          root_file: resume.tex
          latexmk_use_lualatex: true
          
      # format datetime to 'v2021.6.26'
      - name: Set env
        run: echo "::set-env name=NOW::$(date +'v%Y.%m.%d')"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
          
      # check if tag already exists in current day. If so, it will 
      # delete the current tag and replace with the new one
      
      # check if tag already exists
      - uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with: 
          tag: ${{ env.NOW }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # delete tag if exists
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        if: ${{ steps.checkTag.outputs.exists }}
        with:
          delete_release: true # default: false
          tag_name: ${{ env.NOW }} # tag name to delete
          repo: anthonyive/resume # target repo (optional). defaults to repo running this action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # create release
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "resume.pdf"
          tag: ${{ env.NOW }}
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
```
</details>
