### ISSUE TITLE
Tag references commit in master branch, not the branch that the action is running on.

### ISSUE THREAD

**Issue by JonErickson** [ncipollo/release-action#87]
**Describe the bug**
I have two main branches in my repo, master and releases/*. Active development happens under the releases branch and then merged into master when deploying for production. I use paulhatch/semantic-version to obtain the release version which works as expected. The issue is, when I push to my releases branch where the actions below are included in the workflow, the release is tagged to the latest commit of the master branch, not the releases branch, which is technically in the past. How do I get the release tag to attach to the most recent commit in the releases branch? 

**To Reproduce**
```
- name: Get Application Version
  id: semantic_version
  uses: paulhatch/semantic-version@v4.0.2
  with:
    tag_prefix: "v"
    major_pattern: "(MAJOR)"
    minor_pattern: "(MINOR)"
    format: "${major}.${minor}.${patch}"
    short_tags: false
    bump_each_commit: false

- name: Create GitHub Release
  uses: ncipollo/release-action@v1
  with:
    artifacts: build_v${{ steps.semantic_version.outputs.version }}.zip
    tag: v${{ steps.semantic_version.outputs.version }}
    commit: ${{ env.GITHUB_SHA }}
    name: v${{ steps.semantic_version.outputs.version }}
    token: ${{ secrets.GITHUB_TOKEN }}
```

**Expected behavior**
I would like the release to reference the most recent commit in the releases branch, not the master branch.
